export class SampleData {
  public static userPlaylists: MusicKit.Playlists[] = [
    {
      id: "pl.096430726d874e81b0f7dcfb1019104a",
      type: "playlists",
      href: "/v1/catalog/us/playlists/pl.096430726d874e81b0f7dcfb1019104a",
      attributes: {
        curatorName: "Apple Music Alternative",
        lastModifiedDate: "2022-01-11T18:54:52Z",
        audioTraits: [],
        supportsSing: false,
        name: "Muse: Deep Cuts",
        isChart: false,
        description: {
          standard:
            'Find Muse\'s darkest, most menacing dystopian fantasias here—and it\'s not just when Matt Bellamy\'s falsetto breaks open the sky on brutal rock attack "Futurism" or when he sinisterly simmers over a prancing piano on "Sunburn." Just wait until you reach the Queen- and 1984-inspired drama "United States of Eurasia" and squealing rock epic "Defector" to let the anxiety fully set in.',
          short:
            "The British band's darkest, most menacing dystopian fantasias.",
        },
        playlistType: "editorial",
        editorialNotes: {
          name: "Muse: Deep Cuts",
          standard:
            'Find Muse\'s darkest, most menacing dystopian fantasias here—and it\'s not just when Matt Bellamy\'s falsetto breaks open the sky on brutal rock attack "Futurism" or when he sinisterly simmers over a prancing piano on "Sunburn." Just wait until you reach the Queen- and 1984-inspired drama "United States of Eurasia" and squealing rock epic "Defector" to let the anxiety fully set in.',
          short:
            "The British band's darkest, most menacing dystopian fantasias.",
        },
        artwork: {
          width: 1080,
          url: "https://is3-ssl.mzstatic.com/image/thumb/Music116/v4/e6/06/6a/e6066a94-834e-2764-a71b-89cea53ec256/pr_source.png/{w}x{h}SC.FPDC02.jpg?l=en-US",
          height: 1080,
          textColor3: "a6a6a7",
          textColor2: "04c5fc",
          textColor4: "059fcd",
          textColor1: "cdcdcd",
          bgColor: "090910",
          hasP3: false,
        },
        playParams: {
          id: "pl.096430726d874e81b0f7dcfb1019104a",
          kind: "playlist",
          versionHash:
            "2ee3d93f619767c3f55ac4ac1666c559994ebde098f1d782ff47b31706517f38",
        },
        url: "https://music.apple.com/us/playlist/muse-deep-cuts/pl.096430726d874e81b0f7dcfb1019104a",
      },
      relationships: {
        tracks: {
          href: "/v1/catalog/us/playlists/pl.096430726d874e81b0f7dcfb1019104a/tracks",
          data: [
            {
              id: "973556129",
              type: "songs",
              href: "/v1/catalog/us/songs/973556129",
              attributes: {
                hasTimeSyncedLyrics: true,
                albumName: "Drones",
                genreNames: ["Alternative", "Music"],
                trackNumber: 10,
                releaseDate: "2015-06-05",
                durationInMillis: 347997,
                isVocalAttenuationAllowed: true,
                isMasteredForItunes: true,
                isrc: "GBAHT1500063",
                artwork: {
                  width: 2400,
                  url: "https://is2-ssl.mzstatic.com/image/thumb/Music125/v4/fe/e2/d0/fee2d0c2-a1cc-4804-97d5-0db67a7895ed/825646121205.jpg/{w}x{h}bb.jpg",
                  height: 2400,
                  textColor3: "b3b4af",
                  textColor2: "cacdbd",
                  textColor4: "a2a498",
                  textColor1: "e0e1da",
                  bgColor: "010101",
                  hasP3: false,
                },
                composerName: "Matthew Bellamy",
                audioLocale: "en-US",
                url: "https://music.apple.com/us/album/aftermath/973555620?i=973556129",
                playParams: {
                  id: "973556129",
                  kind: "song",
                },
                discNumber: 1,
                hasLyrics: true,
                isAppleDigitalMaster: true,
                audioTraits: ["lossless", "lossy-stereo"],
                name: "Aftermath",
                previews: [
                  {
                    url: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/9a/2f/97/9a2f97c5-03d0-3e8e-37c4-7bb692a7f579/mzaf_6041890430247811376.plus.aac.ep.m4a",
                  },
                ],
                artistName: "Muse",
              },
            },
            {
              id: "991509855",
              type: "songs",
              href: "/v1/catalog/us/songs/991509855",
              attributes: {
                hasTimeSyncedLyrics: true,
                albumName: "The Resistance",
                genreNames: ["Alternative", "Music"],
                trackNumber: 6,
                releaseDate: "2009-09-11",
                durationInMillis: 414960,
                isVocalAttenuationAllowed: true,
                isMasteredForItunes: true,
                isrc: "GBAHT1500313",
                artwork: {
                  width: 1425,
                  url: "https://is5-ssl.mzstatic.com/image/thumb/Music115/v4/53/13/26/531326a2-b93d-9ab8-30cc-e4a9392e7b86/825646092666.jpg/{w}x{h}bb.jpg",
                  height: 1425,
                  textColor3: "bab8ba",
                  textColor2: "cacaca",
                  textColor4: "a4a2a6",
                  textColor1: "e6e6e4",
                  bgColor: "090214",
                  hasP3: false,
                },
                composerName: "Matthew Bellamy",
                audioLocale: "en-US",
                url: "https://music.apple.com/us/album/unnatural-selection/991509751?i=991509855",
                playParams: {
                  id: "991509855",
                  kind: "song",
                },
                discNumber: 1,
                hasLyrics: true,
                isAppleDigitalMaster: true,
                audioTraits: ["lossless", "lossy-stereo"],
                name: "Unnatural Selection",
                previews: [
                  {
                    url: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/14/d9/83/14d983f5-51c7-4608-f608-9efbab3900cc/mzaf_13194220942371788413.plus.aac.ep.m4a",
                  },
                ],
                artistName: "Muse",
              },
            },
            {
              id: "1440780532",
              type: "songs",
              href: "/v1/catalog/us/songs/1440780532",
              attributes: {
                hasTimeSyncedLyrics: true,
                albumName: "Simulation Theory (Super Deluxe)",
                genreNames: ["Alternative", "Music"],
                trackNumber: 8,
                releaseDate: "2018-11-09",
                durationInMillis: 244719,
                isVocalAttenuationAllowed: true,
                isMasteredForItunes: true,
                isrc: "GBAHT1800372",
                artwork: {
                  width: 4000,
                  url: "https://is1-ssl.mzstatic.com/image/thumb/Music114/v4/3d/e5/ce/3de5cef0-83f1-4320-73e2-b32eae427634/190295559199.jpg/{w}x{h}bb.jpg",
                  height: 4000,
                  textColor3: "c497b1",
                  textColor2: "e886d0",
                  textColor4: "c36ba6",
                  textColor1: "e8bcdd",
                  bgColor: "330001",
                  hasP3: false,
                },
                composerName: "Johan Schuster & Matthew Bellamy",
                audioLocale: "en-US",
                url: "https://music.apple.com/us/album/get-up-and-fight/1440779866?i=1440780532",
                playParams: {
                  id: "1440780532",
                  kind: "song",
                },
                discNumber: 1,
                hasLyrics: true,
                isAppleDigitalMaster: true,
                audioTraits: ["hi-res-lossless", "lossless", "lossy-stereo"],
                name: "Get Up and Fight",
                previews: [
                  {
                    url: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/1b/32/76/1b327615-54a9-a704-0af5-e20444364583/mzaf_3078748977737814814.plus.aac.ep.m4a",
                  },
                ],
                artistName: "Muse",
              },
            },
            {
              id: "973556128",
              type: "songs",
              href: "/v1/catalog/us/songs/973556128",
              attributes: {
                hasTimeSyncedLyrics: true,
                albumName: "Drones",
                genreNames: ["Alternative", "Music"],
                trackNumber: 9,
                releaseDate: "2015-06-05",
                durationInMillis: 245711,
                isVocalAttenuationAllowed: true,
                isMasteredForItunes: true,
                isrc: "GBAHT1500062",
                artwork: {
                  width: 2400,
                  url: "https://is2-ssl.mzstatic.com/image/thumb/Music125/v4/fe/e2/d0/fee2d0c2-a1cc-4804-97d5-0db67a7895ed/825646121205.jpg/{w}x{h}bb.jpg",
                  height: 2400,
                  textColor3: "b3b4af",
                  textColor2: "cacdbd",
                  textColor4: "a2a498",
                  textColor1: "e0e1da",
                  bgColor: "010101",
                  hasP3: false,
                },
                composerName: "Matthew Bellamy",
                audioLocale: "en-US",
                url: "https://music.apple.com/us/album/revolt/973555620?i=973556128",
                playParams: {
                  id: "973556128",
                  kind: "song",
                },
                discNumber: 1,
                hasLyrics: true,
                isAppleDigitalMaster: true,
                audioTraits: ["lossless", "lossy-stereo"],
                name: "Revolt",
                previews: [
                  {
                    url: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/f6/5e/db/f65edb24-89fc-7886-8282-16bec46c0abb/mzaf_11845642672907514615.plus.aac.ep.m4a",
                  },
                ],
                artistName: "Muse",
              },
            },
            {
              id: "991510695",
              type: "songs",
              href: "/v1/catalog/us/songs/991510695",
              attributes: {
                hasTimeSyncedLyrics: true,
                albumName: "Absolution",
                genreNames: ["Alternative", "Music"],
                trackNumber: 13,
                releaseDate: "2003-09-15",
                durationInMillis: 191376,
                isVocalAttenuationAllowed: true,
                isMasteredForItunes: true,
                isrc: "GBAHT1500280",
                artwork: {
                  width: 1425,
                  url: "https://is4-ssl.mzstatic.com/image/thumb/Music124/v4/a9/04/e3/a904e322-42b9-17ea-2087-eca27381bcf3/825646095971.jpg/{w}x{h}bb.jpg",
                  height: 1425,
                  textColor3: "373432",
                  textColor2: "182330",
                  textColor4: "3e4750",
                  textColor1: "100c09",
                  bgColor: "d6d6d4",
                  hasP3: false,
                },
                composerName:
                  "Chris Wolstenholme, Dominic Howard & Matthew Bellamy",
                audioLocale: "en-US",
                url: "https://music.apple.com/us/album/thoughts-of-a-dying-atheist/991510292?i=991510695",
                playParams: {
                  id: "991510695",
                  kind: "song",
                },
                discNumber: 1,
                hasLyrics: true,
                isAppleDigitalMaster: true,
                audioTraits: ["lossless", "lossy-stereo"],
                name: "Thoughts of a Dying Atheist",
                previews: [
                  {
                    url: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/4d/5c/59/4d5c5943-66ad-a522-8964-4f66dbb8e07c/mzaf_4671504455695061069.plus.aac.ep.m4a",
                  },
                ],
                artistName: "Muse",
              },
            },
            {
              id: "991509857",
              type: "songs",
              href: "/v1/catalog/us/songs/991509857",
              attributes: {
                hasTimeSyncedLyrics: false,
                albumName: "The Resistance",
                genreNames: ["Alternative", "Music"],
                trackNumber: 8,
                releaseDate: "2009-09-11",
                durationInMillis: 338813,
                isVocalAttenuationAllowed: false,
                isMasteredForItunes: true,
                isrc: "GBAHT1500315",
                artwork: {
                  width: 1425,
                  url: "https://is5-ssl.mzstatic.com/image/thumb/Music115/v4/53/13/26/531326a2-b93d-9ab8-30cc-e4a9392e7b86/825646092666.jpg/{w}x{h}bb.jpg",
                  height: 1425,
                  textColor3: "bab8ba",
                  textColor2: "cacaca",
                  textColor4: "a4a2a6",
                  textColor1: "e6e6e4",
                  bgColor: "090214",
                  hasP3: false,
                },
                composerName: "Camille Saint-Saëns & Matthew Bellamy",
                audioLocale: "en-US",
                url: "https://music.apple.com/us/album/i-belong-to-you-mon-coeur-souvre-a-ta-voix/991509751?i=991509857",
                playParams: {
                  id: "991509857",
                  kind: "song",
                },
                discNumber: 1,
                hasLyrics: true,
                isAppleDigitalMaster: true,
                audioTraits: ["lossless", "lossy-stereo"],
                name: "I Belong to You (+Mon Coeur S'Ouvre a Ta Voix)",
                previews: [
                  {
                    url: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/0b/d7/7c/0bd77c44-7328-3534-08c2-bccfa1d59bd6/mzaf_14327267898155142.plus.aac.ep.m4a",
                  },
                ],
                artistName: "Muse",
              },
            },
            {
              id: "992221999",
              type: "songs",
              href: "/v1/catalog/us/songs/992221999",
              attributes: {
                hasTimeSyncedLyrics: true,
                albumName: "Black Holes and Revelations",
                genreNames: ["Alternative", "Music"],
                trackNumber: 5,
                releaseDate: "2006-06-19",
                durationInMillis: 123193,
                isVocalAttenuationAllowed: true,
                isMasteredForItunes: true,
                isrc: "GBAHT1500287",
                artwork: {
                  width: 1425,
                  url: "https://is5-ssl.mzstatic.com/image/thumb/Music124/v4/4a/c1/5d/4ac15dc9-2ae6-1d5b-3add-43bae227f941/825646095452.jpg/{w}x{h}bb.jpg",
                  height: 1425,
                  textColor3: "dec5ca",
                  textColor2: "e4c28f",
                  textColor4: "d4a376",
                  textColor1: "efecf8",
                  bgColor: "972814",
                  hasP3: false,
                },
                composerName: "Matthew Bellamy",
                audioLocale: "en-US",
                url: "https://music.apple.com/us/album/soldiers-poem/992221994?i=992221999",
                playParams: {
                  id: "992221999",
                  kind: "song",
                },
                discNumber: 1,
                hasLyrics: true,
                isAppleDigitalMaster: true,
                audioTraits: ["lossless", "lossy-stereo"],
                name: "Soldier's Poem",
                previews: [
                  {
                    url: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/d2/2b/dd/d22bddc5-684c-af16-9b48-341c0bd4f8fc/mzaf_9207383489109285250.plus.aac.p.m4a",
                  },
                ],
                artistName: "Muse",
              },
            },
            {
              id: "319620942",
              type: "songs",
              href: "/v1/catalog/us/songs/319620942",
              attributes: {
                hasTimeSyncedLyrics: true,
                albumName: "Dead Star / In Your World - EP",
                genreNames: ["Pop", "Music", "Rock", "Adult Alternative"],
                trackNumber: 4,
                releaseDate: "2002-06-17",
                durationInMillis: 211031,
                isVocalAttenuationAllowed: true,
                isMasteredForItunes: false,
                isrc: "GBAHT0900234",
                artwork: {
                  width: 1425,
                  url: "https://is3-ssl.mzstatic.com/image/thumb/Music124/v4/66/69/30/6669306e-b6a7-9113-df7a-2981ea5c2cc2/mzi.dbwwxmfy.jpg/{w}x{h}bb.jpg",
                  height: 1425,
                  textColor3: "c3bbaf",
                  textColor2: "eed19c",
                  textColor4: "c4ad83",
                  textColor1: "ede3d3",
                  bgColor: "1b1b21",
                  hasP3: false,
                },
                composerName: "Bob Crewe & Bob Gaudio",
                audioLocale: "en-US",
                url: "https://music.apple.com/us/album/cant-take-my-eyes-off-you/319620459?i=319620942",
                playParams: {
                  id: "319620942",
                  kind: "song",
                },
                discNumber: 1,
                hasLyrics: true,
                isAppleDigitalMaster: false,
                audioTraits: ["lossless", "lossy-stereo"],
                name: "Can't Take My Eyes Off You",
                previews: [
                  {
                    url: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/b5/40/9c/b5409cfd-aa57-7a39-bbd3-23581f91d208/mzaf_12419182266071256791.plus.aac.ep.m4a",
                  },
                ],
                artistName: "Muse",
              },
            },
            {
              id: "992089115",
              type: "songs",
              href: "/v1/catalog/us/songs/992089115",
              attributes: {
                hasTimeSyncedLyrics: true,
                albumName: "Origin of Symmetry",
                genreNames: ["Alternative", "Music"],
                trackNumber: 7,
                releaseDate: "2001-07-17",
                durationInMillis: 218427,
                isVocalAttenuationAllowed: true,
                isMasteredForItunes: true,
                isrc: "GBAHT1500260",
                artwork: {
                  width: 1425,
                  url: "https://is3-ssl.mzstatic.com/image/thumb/Music114/v4/0c/c8/0b/0cc80b73-aa09-492d-4fcc-984cab29acfa/825646096909.jpg/{w}x{h}bb.jpg",
                  height: 1425,
                  textColor3: "36280d",
                  textColor2: "2d2211",
                  textColor4: "513b14",
                  textColor1: "0c0a09",
                  bgColor: "dfa31e",
                  hasP3: false,
                },
                composerName: "Matthew Bellamy",
                audioLocale: "en-US",
                url: "https://music.apple.com/us/album/micro-cuts/992088658?i=992089115",
                playParams: {
                  id: "992089115",
                  kind: "song",
                },
                discNumber: 1,
                hasLyrics: true,
                isAppleDigitalMaster: true,
                audioTraits: ["lossless", "lossy-stereo"],
                name: "Micro Cuts",
                previews: [
                  {
                    url: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/d9/dd/bb/d9ddbb14-fa90-1698-b9f6-bf993997dd2c/mzaf_9780056520309508513.plus.aac.ep.m4a",
                  },
                ],
                artistName: "Muse",
              },
            },
            {
              id: "991510693",
              type: "songs",
              href: "/v1/catalog/us/songs/991510693",
              attributes: {
                hasTimeSyncedLyrics: true,
                albumName: "Absolution",
                genreNames: ["Alternative", "Music"],
                trackNumber: 11,
                releaseDate: "2003-09-15",
                durationInMillis: 209296,
                isVocalAttenuationAllowed: true,
                isMasteredForItunes: true,
                isrc: "GBAHT1500278",
                artwork: {
                  width: 1425,
                  url: "https://is4-ssl.mzstatic.com/image/thumb/Music124/v4/a9/04/e3/a904e322-42b9-17ea-2087-eca27381bcf3/825646095971.jpg/{w}x{h}bb.jpg",
                  height: 1425,
                  textColor3: "373432",
                  textColor2: "182330",
                  textColor4: "3e4750",
                  textColor1: "100c09",
                  bgColor: "d6d6d4",
                  hasP3: false,
                },
                composerName:
                  "Chris Wolstenholme, Dominic Howard & Matthew Bellamy",
                audioLocale: "en-US",
                url: "https://music.apple.com/us/album/the-small-print/991510292?i=991510693",
                playParams: {
                  id: "991510693",
                  kind: "song",
                },
                discNumber: 1,
                hasLyrics: true,
                isAppleDigitalMaster: true,
                audioTraits: ["lossless", "lossy-stereo"],
                name: "The Small Print",
                previews: [
                  {
                    url: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/0a/af/be/0aafbe53-5f44-5c88-d4f0-452eab3c7c48/mzaf_13607756216473440377.plus.aac.ep.m4a",
                  },
                ],
                artistName: "Muse",
              },
            },
            {
              id: "138265822",
              type: "songs",
              href: "/v1/catalog/us/songs/138265822",
              attributes: {
                hasTimeSyncedLyrics: true,
                albumName: "Hullabaloo Soundtrack",
                genreNames: [
                  "Alternative",
                  "Music",
                  "Rock",
                  "Adult Alternative",
                ],
                trackNumber: 5,
                releaseDate: "2001-06-03",
                durationInMillis: 263600,
                isVocalAttenuationAllowed: true,
                isMasteredForItunes: false,
                isrc: "GBCVT0200036",
                artwork: {
                  width: 1417,
                  url: "https://is5-ssl.mzstatic.com/image/thumb/Music/95/cc/c1/mzi.edlnrsfr.jpg/{w}x{h}bb.jpg",
                  height: 1417,
                  textColor3: "c9d3d2",
                  textColor2: "a4dccc",
                  textColor4: "83b8aa",
                  textColor1: "fcffff",
                  bgColor: "01261f",
                  hasP3: false,
                },
                composerName: "Matthew Bellamy",
                audioLocale: "en-US",
                url: "https://music.apple.com/us/album/map-of-your-head/138270199?i=138265822",
                playParams: {
                  id: "138265822",
                  kind: "song",
                },
                discNumber: 1,
                hasLyrics: true,
                isAppleDigitalMaster: false,
                audioTraits: ["lossless", "lossy-stereo"],
                name: "Map of Your Head",
                previews: [
                  {
                    url: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/49/21/05/492105c1-4e56-b26f-2742-b71bc1e2d18a/mzaf_17889672819454752151.plus.aac.ep.m4a",
                  },
                ],
                artistName: "Muse",
              },
            },
            {
              id: "1440780539",
              type: "songs",
              href: "/v1/catalog/us/songs/1440780539",
              attributes: {
                hasTimeSyncedLyrics: true,
                albumName: "Simulation Theory (Super Deluxe)",
                genreNames: ["Alternative", "Music"],
                trackNumber: 9,
                releaseDate: "2018-11-09",
                durationInMillis: 230690,
                isVocalAttenuationAllowed: true,
                isMasteredForItunes: true,
                isrc: "GBAHT1800374",
                artwork: {
                  width: 4000,
                  url: "https://is1-ssl.mzstatic.com/image/thumb/Music114/v4/3d/e5/ce/3de5cef0-83f1-4320-73e2-b32eae427634/190295559199.jpg/{w}x{h}bb.jpg",
                  height: 4000,
                  textColor3: "c497b1",
                  textColor2: "e886d0",
                  textColor4: "c36ba6",
                  textColor1: "e8bcdd",
                  bgColor: "330001",
                  hasP3: false,
                },
                composerName: "Matthew Bellamy",
                audioLocale: "en-US",
                url: "https://music.apple.com/us/album/blockades/1440779866?i=1440780539",
                playParams: {
                  id: "1440780539",
                  kind: "song",
                },
                discNumber: 1,
                hasLyrics: true,
                isAppleDigitalMaster: true,
                audioTraits: ["lossless", "lossy-stereo"],
                name: "Blockades",
                previews: [
                  {
                    url: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/db/30/b9/db30b94e-d3a0-2ef4-cb12-dd8bec747a63/mzaf_6559203348330860689.plus.aac.ep.m4a",
                  },
                ],
                artistName: "Muse",
              },
            },
            {
              id: "563015722",
              type: "songs",
              href: "/v1/catalog/us/songs/563015722",
              attributes: {
                hasTimeSyncedLyrics: true,
                albumName: "The 2nd Law (Deluxe Version)",
                genreNames: ["Alternative", "Music"],
                trackNumber: 7,
                releaseDate: "2012-09-28",
                durationInMillis: 262821,
                isVocalAttenuationAllowed: true,
                isMasteredForItunes: true,
                isrc: "GBAHT1200406",
                artwork: {
                  width: 2400,
                  url: "https://is2-ssl.mzstatic.com/image/thumb/Music125/v4/b8/50/04/b850045b-bfab-77de-040b-94b13c6f79ef/825646557646.jpg/{w}x{h}bb.jpg",
                  height: 2400,
                  textColor3: "cfcfcf",
                  textColor2: "4ed376",
                  textColor4: "42ac62",
                  textColor1: "ffffff",
                  bgColor: "111111",
                  hasP3: false,
                },
                composerName: "Matthew Bellamy",
                audioLocale: "en-US",
                url: "https://music.apple.com/us/album/animals/563015686?i=563015722",
                playParams: {
                  id: "563015722",
                  kind: "song",
                },
                discNumber: 1,
                hasLyrics: true,
                isAppleDigitalMaster: true,
                audioTraits: ["lossless", "lossy-stereo"],
                name: "Animals",
                previews: [
                  {
                    url: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/17/31/cc/1731cc42-f734-54d5-b99d-ff4432ef7fb4/mzaf_12034645582042892062.plus.aac.ep.m4a",
                  },
                ],
                artistName: "Muse",
              },
            },
            {
              id: "992089117",
              type: "songs",
              href: "/v1/catalog/us/songs/992089117",
              attributes: {
                hasTimeSyncedLyrics: true,
                albumName: "Origin of Symmetry",
                genreNames: ["Alternative", "Music"],
                trackNumber: 9,
                releaseDate: "2001-07-17",
                durationInMillis: 287523,
                isVocalAttenuationAllowed: true,
                isMasteredForItunes: true,
                isrc: "GBAHT1500262",
                artwork: {
                  width: 1425,
                  url: "https://is3-ssl.mzstatic.com/image/thumb/Music114/v4/0c/c8/0b/0cc80b73-aa09-492d-4fcc-984cab29acfa/825646096909.jpg/{w}x{h}bb.jpg",
                  height: 1425,
                  textColor3: "36280d",
                  textColor2: "2d2211",
                  textColor4: "513b14",
                  textColor1: "0c0a09",
                  bgColor: "dfa31e",
                  hasP3: false,
                },
                composerName: "Matthew Bellamy",
                audioLocale: "en-US",
                url: "https://music.apple.com/us/album/darkshines/992088658?i=992089117",
                playParams: {
                  id: "992089117",
                  kind: "song",
                },
                discNumber: 1,
                hasLyrics: true,
                isAppleDigitalMaster: true,
                audioTraits: ["lossless", "lossy-stereo"],
                name: "Darkshines",
                previews: [
                  {
                    url: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/b0/c7/ca/b0c7ca61-d706-5ce1-0322-963862e1af30/mzaf_3894231544062758072.plus.aac.ep.m4a",
                  },
                ],
                artistName: "Muse",
              },
            },
            {
              id: "991509856",
              type: "songs",
              href: "/v1/catalog/us/songs/991509856",
              attributes: {
                hasTimeSyncedLyrics: true,
                albumName: "The Resistance",
                genreNames: ["Alternative", "Music"],
                trackNumber: 7,
                releaseDate: "2009-09-11",
                durationInMillis: 246093,
                isVocalAttenuationAllowed: true,
                isMasteredForItunes: true,
                isrc: "GBAHT1500314",
                artwork: {
                  width: 1425,
                  url: "https://is5-ssl.mzstatic.com/image/thumb/Music115/v4/53/13/26/531326a2-b93d-9ab8-30cc-e4a9392e7b86/825646092666.jpg/{w}x{h}bb.jpg",
                  height: 1425,
                  textColor3: "bab8ba",
                  textColor2: "cacaca",
                  textColor4: "a4a2a6",
                  textColor1: "e6e6e4",
                  bgColor: "090214",
                  hasP3: false,
                },
                composerName: "Matthew Bellamy",
                audioLocale: "en-US",
                url: "https://music.apple.com/us/album/mk-ultra/991509751?i=991509856",
                playParams: {
                  id: "991509856",
                  kind: "song",
                },
                discNumber: 1,
                hasLyrics: true,
                isAppleDigitalMaster: true,
                audioTraits: ["lossless", "lossy-stereo"],
                name: "MK Ultra",
                previews: [
                  {
                    url: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/9d/4b/eb/9d4bebbc-81f9-5d79-ca31-678f9755a787/mzaf_15868483110439632334.plus.aac.ep.m4a",
                  },
                ],
                artistName: "Muse",
              },
            },
            {
              id: "992222003",
              type: "songs",
              href: "/v1/catalog/us/songs/992222003",
              attributes: {
                hasTimeSyncedLyrics: true,
                albumName: "Black Holes and Revelations",
                genreNames: ["Alternative", "Music"],
                trackNumber: 9,
                releaseDate: "2006-06-19",
                durationInMillis: 288191,
                isVocalAttenuationAllowed: true,
                isMasteredForItunes: true,
                isrc: "GBAHT1500291",
                artwork: {
                  width: 1425,
                  url: "https://is5-ssl.mzstatic.com/image/thumb/Music124/v4/4a/c1/5d/4ac15dc9-2ae6-1d5b-3add-43bae227f941/825646095452.jpg/{w}x{h}bb.jpg",
                  height: 1425,
                  textColor3: "dec5ca",
                  textColor2: "e4c28f",
                  textColor4: "d4a376",
                  textColor1: "efecf8",
                  bgColor: "972814",
                  hasP3: false,
                },
                composerName: "Matthew Bellamy",
                audioLocale: "en-US",
                url: "https://music.apple.com/us/album/city-of-delusion/992221994?i=992222003",
                playParams: {
                  id: "992222003",
                  kind: "song",
                },
                discNumber: 1,
                hasLyrics: true,
                isAppleDigitalMaster: true,
                audioTraits: ["lossless", "lossy-stereo"],
                name: "City of Delusion",
                previews: [
                  {
                    url: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/90/7a/a7/907aa778-f060-dcc4-ef57-cc62979fc21b/mzaf_2221372197506774795.plus.aac.ep.m4a",
                  },
                ],
                artistName: "Muse",
              },
            },
            {
              id: "991510696",
              type: "songs",
              href: "/v1/catalog/us/songs/991510696",
              attributes: {
                hasTimeSyncedLyrics: true,
                albumName: "Absolution",
                genreNames: ["Alternative", "Music"],
                trackNumber: 14,
                releaseDate: "2003-09-15",
                durationInMillis: 294536,
                isVocalAttenuationAllowed: true,
                isMasteredForItunes: true,
                isrc: "GBAHT1500281",
                artwork: {
                  width: 1425,
                  url: "https://is4-ssl.mzstatic.com/image/thumb/Music124/v4/a9/04/e3/a904e322-42b9-17ea-2087-eca27381bcf3/825646095971.jpg/{w}x{h}bb.jpg",
                  height: 1425,
                  textColor3: "373432",
                  textColor2: "182330",
                  textColor4: "3e4750",
                  textColor1: "100c09",
                  bgColor: "d6d6d4",
                  hasP3: false,
                },
                composerName:
                  "Chris Wolstenholme, Dominic Howard & Matthew Bellamy",
                audioLocale: "en-US",
                url: "https://music.apple.com/us/album/ruled-by-secrecy/991510292?i=991510696",
                playParams: {
                  id: "991510696",
                  kind: "song",
                },
                discNumber: 1,
                hasLyrics: true,
                isAppleDigitalMaster: true,
                audioTraits: ["lossless", "lossy-stereo"],
                name: "Ruled By Secrecy",
                previews: [
                  {
                    url: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/ae/bd/0d/aebd0d8c-1c63-f9b5-902b-48f0a0251bcb/mzaf_3798860322227208356.plus.aac.ep.m4a",
                  },
                ],
                artistName: "Muse",
              },
            },
            {
              id: "992222004",
              type: "songs",
              href: "/v1/catalog/us/songs/992222004",
              attributes: {
                hasTimeSyncedLyrics: true,
                albumName: "Black Holes and Revelations",
                genreNames: ["Alternative", "Music"],
                trackNumber: 10,
                releaseDate: "2006-06-19",
                durationInMillis: 223317,
                isVocalAttenuationAllowed: true,
                isMasteredForItunes: true,
                isrc: "GBAHT1500292",
                artwork: {
                  width: 1425,
                  url: "https://is5-ssl.mzstatic.com/image/thumb/Music124/v4/4a/c1/5d/4ac15dc9-2ae6-1d5b-3add-43bae227f941/825646095452.jpg/{w}x{h}bb.jpg",
                  height: 1425,
                  textColor3: "dec5ca",
                  textColor2: "e4c28f",
                  textColor4: "d4a376",
                  textColor1: "efecf8",
                  bgColor: "972814",
                  hasP3: false,
                },
                composerName: "Matthew Bellamy",
                audioLocale: "en-US",
                url: "https://music.apple.com/us/album/hoodoo/992221994?i=992222004",
                playParams: {
                  id: "992222004",
                  kind: "song",
                },
                discNumber: 1,
                hasLyrics: true,
                isAppleDigitalMaster: true,
                audioTraits: ["lossless", "lossy-stereo"],
                name: "Hoodoo",
                previews: [
                  {
                    url: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/74/ab/5d/74ab5d5d-95b8-f6b8-36f3-1550ab15871c/mzaf_18351764192701212219.plus.aac.ep.m4a",
                  },
                ],
                artistName: "Muse",
              },
            },
            {
              id: "991516218",
              type: "songs",
              href: "/v1/catalog/us/songs/991516218",
              attributes: {
                hasTimeSyncedLyrics: true,
                albumName: "Showbiz",
                genreNames: ["Alternative", "Music"],
                trackNumber: 8,
                releaseDate: "1999-06-14",
                durationInMillis: 218902,
                isVocalAttenuationAllowed: true,
                isMasteredForItunes: true,
                isrc: "GBAHT1500249",
                artwork: {
                  width: 1425,
                  url: "https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/e9/78/cb/e978cb04-1320-409d-ebec-a2c247df0353/825646097340.jpg/{w}x{h}bb.jpg",
                  height: 1425,
                  textColor3: "3d87af",
                  textColor2: "3da4df",
                  textColor4: "3184b5",
                  textColor1: "4da8d9",
                  bgColor: "00010b",
                  hasP3: false,
                },
                composerName: "Matthew Bellamy",
                audioLocale: "en-US",
                url: "https://music.apple.com/us/album/uno/991516209?i=991516218",
                playParams: {
                  id: "991516218",
                  kind: "song",
                },
                discNumber: 1,
                hasLyrics: true,
                isAppleDigitalMaster: true,
                audioTraits: ["lossless", "lossy-stereo"],
                name: "Uno",
                previews: [
                  {
                    url: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/24/19/c3/2419c32d-19e3-9b3e-274d-5e70d9e178a9/mzaf_16570844467637810690.plus.aac.ep.m4a",
                  },
                ],
                artistName: "Muse",
              },
            },
            {
              id: "991509847",
              type: "songs",
              href: "/v1/catalog/us/songs/991509847",
              attributes: {
                hasTimeSyncedLyrics: true,
                albumName: "The Resistance",
                genreNames: ["Alternative", "Music"],
                trackNumber: 4,
                releaseDate: "2009-09-11",
                durationInMillis: 347813,
                isVocalAttenuationAllowed: true,
                isMasteredForItunes: true,
                isrc: "GBAHT1500311",
                artwork: {
                  width: 1425,
                  url: "https://is5-ssl.mzstatic.com/image/thumb/Music115/v4/53/13/26/531326a2-b93d-9ab8-30cc-e4a9392e7b86/825646092666.jpg/{w}x{h}bb.jpg",
                  height: 1425,
                  textColor3: "bab8ba",
                  textColor2: "cacaca",
                  textColor4: "a4a2a6",
                  textColor1: "e6e6e4",
                  bgColor: "090214",
                  hasP3: false,
                },
                composerName: "Frédéric Chopin & Matthew Bellamy",
                audioLocale: "en-US",
                url: "https://music.apple.com/us/album/united-states-of-eurasia-collateral-damage/991509751?i=991509847",
                playParams: {
                  id: "991509847",
                  kind: "song",
                },
                discNumber: 1,
                hasLyrics: true,
                isAppleDigitalMaster: true,
                audioTraits: ["lossless", "lossy-stereo"],
                name: "United States of Eurasia (+Collateral Damage)",
                previews: [
                  {
                    url: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/eb/25/92/eb2592eb-982c-da0f-f2a3-ca3d41c99704/mzaf_1050381964280277105.plus.aac.ep.m4a",
                  },
                ],
                artistName: "Muse",
              },
            },
          ],
        },
        curator: {
          href: "/v1/catalog/us/playlists/pl.096430726d874e81b0f7dcfb1019104a/curator",
          data: [
            {
              id: "976439526",
              type: "apple-curators",
              href: "/v1/catalog/us/apple-curators/976439526",
            },
          ],
        },
      },
    },
  ];

  public static homeRecommendations = {};
}
